# Generated by Django 4.0.4 on 2022-05-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
